---
title: "LAGOS lake depth"
output: pdf_document
---

```{r setup, include=FALSE}
# https://stackoverflow.com/a/24600461/3362993
knitr::knit_hooks$set(timeit = local({
  now = NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res = difftime(Sys.time(), now)
      now <<- NULL
      # use options$label if you want the chunk label as well
      paste('Time for this code chunk:', as.character(round(res, 2)))
    }
  }})
)

knitr::opts_chunk$set(echo = FALSE, timeit = TRUE, eval = FALSE)
source("scripts/99_utils.R")
```

```{r data, message=FALSE, echo=FALSE, eval=TRUE}
dt <- read.csv("data/lagosus_depth.csv", stringsAsFactors = FALSE) %>%
  mutate(maxdepth_class = cut(max_depth_m, 
                     round(quantile(max_depth_m, c(0, 0.05, 0.5, 0.95, 1), 
                                    na.rm = TRUE)))) %>% 
  coordinatize(latname = "lat", longname = "long")
```

 * Number of lakes w/ max depth by state
 
 * Fraction of lakes w/ max depth by state
 
 * Ridgeline plot of lake depth
 
```{r summary_stats, echo = FALSE, eval=FALSE}
paste0(round(sum(!is.na(lg_depth$maxdepth)) / nrow(lg_depth) * 100, 2),
       "% (n=", sum(!is.na(lg_depth$maxdepth)), ") of lakes have maxdepth values.")

paste0(round(sum(dplyr::filter(lg_depth, !is.na(maxdepth))$lagoslakeid %in% 
            lg$epi_nutr$lagoslakeid) / 
        nrow(lg_depth) * 100, 2), 
       "% (n=", sum(dplyr::filter(lg_depth, !is.na(maxdepth))$lagoslakeid %in% 
            lg$epi_nutr$lagoslakeid), ") of lakes with maxdepth values have limno data.")

paste0(round(sum(!is.na(dplyr::filter(lg_depth, has_limno)$maxdepth)) / 
  length(unique(lg$epi_nutr$lagoslakeid)) * 100, 2), 
  "% (n=", sum(!is.na(dplyr::filter(lg_depth, has_limno)$maxdepth)), ") of lakes with limno data have maxdepth values.")
```

```{r viz, echo=FALSE, warning=FALSE, message=FALSE, fig.height=3}
knitr::kable(t(quantile(lg_depth$maxdepth, c(0, 0.05, 0.5, 0.95, 1), 
                        na.rm = TRUE)), caption = "Lake depth quantiles")
knitr::kable(round(t(quantile(lg_depth$lake_area_ha, c(0, 0.05, 0.5, 0.95, 1), 
                        na.rm = TRUE)), 2), caption = "Lake area quantiles")

cowplot::plot_grid(
  ggplot(data = dplyr::filter(lg_depth, !is.na(lake_area_ha), !is.na(maxdepth))) + 
    geom_mark_rect(aes(fill = "", x = lake_area_ha, y = maxdepth,
                     filter = maxdepth <= 26 & lake_area_ha <= 53), inherit.aes = FALSE) +
  geom_point(aes(x = lake_area_ha, y = maxdepth)) +
  theme_minimal_grid() + theme(legend.position = 0, 
                               axis.text.x = element_text(angle = 90)) +
  scale_x_log10(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0, 0), limits = c(0, 100)) +
  xlab("log(Lake Area)"), 
  ggplot() + 
    geom_point(data = dplyr::filter(lg_depth, lake_area_ha < 53, maxdepth < 26), 
               aes(x = lake_area_ha, y = maxdepth)) +
    theme_minimal_grid() + 
      xlab("Lake Area")
)

```

```{r map, echo=FALSE, message=FALSE, error = FALSE}
states_base <- jsta::get_intersects(jsta::usa_sf(), lg_depth, 
                                    threshold = 1500)

ggplot() + 
  geom_sf(data = states_base) +
  geom_sf(data = dplyr::sample_frac(
    dplyr::filter(lg_depth, !is.na(maxdepth)), 0.3), 
          aes(color = color), 
    size = 1, alpha = 0.4, shape = 20) +
  # scale_color_viridis_d(direction = -1) +
  # scale_color_brewer(palette = "Set2") +
  scale_fill_brewer(palette = "Set2") +
  coord_sf(datum = NA) + theme_void() +
  labs(color = "depth (m)")
```

```{r papers}
knitr::kable(
  data.frame(stringsAsFactors=FALSE,
  lead_author = c("Hollister", "Heathcote", "Oliver", "Sobek", "Emmerton",
                    "Johansson", "Neumann"),
  year = c(2011L, 2015L, 2016L, 2011L, 2007L, 2007L, 1959L),
  location = c("NE/NY Huc", "Boreal Canada", "LAGOSNE", "Sweden",
                 "Canadian Arctic", "Sweden", "Global"),
  lake_numbers = c(133L, 433L, 7347L, 6618L, 81L, 105L, 107L), 
  rmse_m = c(6, 1.8, 7.1, NA, NA, NA, NA)
))
```

```{r akima}
library(gfplot)
library(dplyr)
library(PBSdata)
library(akima)

bath        <- gfplot:::load_bath(utm_zone = 9) %>% 
  filter(depth > 0) %>%
  filter(X < 600) %>% filter(X > 330) %>%
  filter(Y < 5850) %>% filter(Y > 5630)
bath_interp <- akima::interp(
      x = bath$X,
      y = bath$Y,
      z = log(bath$depth),
      extrap = TRUE, linear = TRUE
    )

z   <- reshape2::melt(bath_interp$z)
z$x <- bath_interp$x[z$Var1]
z$y <- bath_interp$y[z$Var2]
z   <- rename(z, X = x, Y = y, akima_depth = value) %>%
      dplyr::select(-Var1, -Var2) %>%
  filter(!is.na(akima_depth)) %>%
  mutate(akima_depth = exp(akima_depth)) %>%
  dplyr::select(x = X, y = Y, akima_depth)
z   <- raster::rasterFromXYZ(z)

# rasterize bath object. See - https://gis.stackexchange.com/a/79074/32531
bath_ras <- rasterize(bath[,1:2], setValues(z, NA), 
                      bath$depth, fun = mean)


par(mfrow = c(1, 2))
plot(bath_ras)
plot(z)
```

