---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
)
```

## Bathymetry data from thousands of lakes show that difficulty modeling in-lake slope confounds lake depth prediction

### Products

Figures: [manuscript/figures.pdf](manuscript/figures.pdf)

Data: [bathymetry derived depth predictors](data/depth_predictors.csv)

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
taxonomy <- read.csv("data/taxonomy.csv", 
                     stringsAsFactors = FALSE)

# see scripts/99_make_taxonomy.R
dt <- read.csv("data/depth_predictors.csv", 
               stringsAsFactors = FALSE) %>% 
  names() %>%  as.data.frame() %>%  setNames("col_name") %>%
  left_join(taxonomy) %>% data.frame() %>%
  dplyr::filter(!is.na(description)) %>%
  setNames(c("column name", "description", "variable")) %>%
  select(`column name`, variable, description)

options(knitr.kable.NA = '-')
knitr::kable(dt)
```

Data: [bathymetry derived lake depth](data/00_bathy_depth/00_bathy_depth.csv)

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# see scripts/99_make_taxonomy.R
dt       <- read.csv("data/00_bathy_depth/00_bathy_depth.csv", 
               stringsAsFactors = FALSE) %>%
  names() %>%  as.data.frame() %>%  setNames("col_name") %>%
  left_join(taxonomy) %>% data.frame() %>%
  dplyr::filter(!is.na(description)) %>%
  setNames(c("column name", "description", "variable")) %>%
  select(`column name`, variable, description)

knitr::kable(dt)
```
