---
title: Geometric models overestimate lake depth due to imperfect slope measurement

# Use letters for affiliations
author:
  - name: Joseph Stachelek
    affiliation: a
  - name: Patrick Hanly
    affiliation: a
  - name: Patricia A. Soranno
    affiliation: a
  
address:
  - code: a
    address: Department of Fisheries and Wildlife, Michigan State University, 480 Wilson Rd., East Lansing, MI 48824, USA
  
# Optional: line of arbitrary text with additional information.
# Could be used, for example, to mention the bibliographic info in a post-print.
# If not specified, defaults to "This version was compiled on \today"
#date_subtitle: Published in *Journal of Statistical Software*, 2018
# date_subtitle: > 
# This is the accepted version of the following article: J. Stachelek et al., Ecological Applications. In Press, which has been published in final form at DOI:  [DOI](https://doi.org).  This article may be used for non-commercial purposes in accordance with Wiley Terms and Conditions for Use of Self-Archived Versions.

# For footer text  TODO(fold into template, allow free form two-authors)
lead_author_surname: Stachelek et al.

# Place eg a DOI URL or CRAN Package URL here
# doi_footer: "https://doi.org/10.5281/zenodo.3754916"

# Abstract
abstract: |
  Lake depth is a critical characteristic that influences many important ecological processes in lakes. Unfortunately, lake depth measurements are labor-intensive to gather and are only available for a small fraction of lakes globally. Therefore, scientists have tried to predict lake depth from characteristics that are easily obtained for all lakes such as lake surface area or the slope of the land surrounding a lake. One approach for predicting lake depth simulates lake basins using a geometric model where nearshore land slope is assumed to be a representative proxy for in-lake slope and the distance to the center of the lake is assumed to be a representative proxy for the distance to the deepest point of the lake. However, these assumptions have rarely been tested in a broad range of lakes. We used bathymetry data from 5,000 lakes and reservoirs to test these assumptions and to examine whether differences in lake type or shape influences depth prediction error. We found that nearshore land slope was not a representative proxy of in-lake slope and using it for prediction increases prediction error substantially relative to models using true in-lake slope. We also found that models using nearshore land slope as a proxy systematically overpredicts lake depth in concave lakes (i.e. bowl-shaped; up to 18% of lakes in the study population) and reservoir lakes (up to 30% of lakes in the study population), suggesting caution in using geometric models for lake prediction in unsampled lakes.

# Optional: Acknowledgements
acknowledgements: |
  Funding was provided by the US NSF Macrosystems Biology Program grants, DEB-1638679; DEB-1638550, DEB-1638539, DEB-1638554. PAS was also supported by USDA National Institute of Food and Agriculture Hatch Project, Grant Number: 176820. Author contributions: JS conceived of the study, built models, analyzed data, and wrote the paper. PH and PAS provided interpretation of results and edited the paper.

# Optional: One or more keywords
keywords:
  - lake depth
  - bathymetry
  - hypsography
  - geometry
  - slope

# Paper size for the document, values of letter and a4
papersize: letter

# Font size of the document, values of 9pt (default), 10pt, 11pt and 12pt
fontsize: 9pt

# Optional: Force one-column layout, default is two-column
#one_column: true

# Optional: Enables lineno mode, but only if one_column mode is also true
#lineno: true

# Optional: Enable one-sided layout, default is two-sided
#one_sided: true

# Optional: Enable section numbering, default is unnumbered
#numbersections: true

# Optional: Specify the depth of section number, default is 5
#secnumdepth: 5

# Optional: Skip inserting final break between acknowledgements, default is false
skip_final_break: true

# Optional: Bibliography 
bibliography: lagosdepth
biblio-style: jsta

# Optional: Enable a 'Draft' watermark on the document
#watermark: true

# Customize footer, eg by referencing the vignette
# footer_contents: "Agriculture-lake nutrient relationships"

# Produce a pinp document
output: pinp::pinp

# Required: Vignette metadata for inclusion in a package.
vignette: >
  %\VignetteIndexEntry{YourPackage-vignetteentry}
  %\VignetteKeywords{YourPackage, r, anotherkeyword}
  %\VignettePackage{YourPackage}
  %\VignetteEngine{knitr::rmarkdown}
---

## INTRODUCTION

Lake depth is a major factor controlling lake physics, chemistry, and biota
\citep{liSignificantContributionLake2020, feeEffectsLakeSize1996, readSimulating2368Temperate2014}. However, because measured depth data is only available for a small fraction of all lakes, our ability to understand and predict depth-dependent processes is limited. The importance of lake depth, coupled with its limited availability, has led to numerous attempts to predict depth using measures available for all lakes such as lake surface area or the nearshore slope of the land surrounding a lake \citep{heathcotePredictingBathymetricFeatures2015, oliver2016prediction, sobekPredictingDepthVolume2011}. The approaches taken in these studies have been varied. In addition, they have explored a variety of strategies to maximize prediction accuracy such as employing more diverse covariates \citep{oliver2016prediction}, varying lake buffer sizes \citep{heathcotePredictingBathymetricFeatures2015}, or estimating hidden groupings among lakes \citep{sobekPredictingDepthVolume2011}. 

One approach for predicting lake depth involves a geometric model that assumes lake basins correspond to an idealized shape such as a cone, bowl, or an elliptic sinusoid \citep{hollisterPredictingMaximumLake2011, neumannMaximumDepthAverage1959, yigzawNewGlobalStorage2018}. All such geometric models for lake depth prediction involve implicit assumptions about the terms of geometric formulae. In the simplest case, where lakes basins are treated as cones (Eq \ref{eq1}, Figure \ref{fig1}), two assumptions are required to make depth predictions for all lakes: 1) that nearshore land slope is a representative proxy for in-lake slope and 2) that the distance to the center of the lake is a representative proxy for the distance to the deepest point of the lake (Figure 1). This cone model imposes the following fixed (i.e. geometric) relationship between slope and horizontal distance:
\begin{align}
  depth_{geometric} = tan(slope) * distance \label{eq1}
\end{align}

where the product of slope and horizontal distance yields an exact geometric depth estimate (depth_geometric). 

The assumptions of this model as well as other geometric models can be tested by comparing proxy measures of lake geometry against corresponding “true” (i.e. in-lake) values derived from bathymetric maps. However, due to the scarcity of bathymetric map data, few studies have tested these assumptions except in individual studies of very large lakes or for small numbers of lakes (< 100) \citep{johanssonNewApproachesModelling2007}. As a result, it is unclear what effect proxies have on lake depth predictions using geometric models and whether depth predictions are more sensitive to errors in the horizontal dimension (i.e. distance to the deepest point of the lake) or errors in the vertical dimension (i.e. in-lake slope). Additionally it is unclear whether model prediction error is related to differences in lake type such those with different cross-section shapes or those classified as reservoirs versus natural lakes. This information could help direct future research efforts to focus on particular dimensions of lake geometry (i.e. horizontal versus vertical) or to stratify model predictions based on specific lake types and cross-section shapes. 

Given the knowledge gaps identified above, we asked three research questions: 1) Is nearshore land slope representative of in-lake slope; and is the distance to the center of a lake representative of the distance to the deepest point of a lake? 2) How does the use of proxies for lake geometry affect lake depth prediction error? 3) How does lake shape (i.e. concave versus convex) and lake type (i.e. natural lake vs reservoir) affect depth prediction error?

To answer these questions, we extracted the maximum depth (hereafter referred to as “observed maximum depth”), in-lake slope, shape (i.e., concave versus convex), and distance to the deepest point, of approximately 5,000 lakes in the Northeastern and Midwestern US from bathymetric map data. First, we examined whether measures of lake geometry (in-lake slope and distance to the deepest point of lakes) were related to geometry proxies (nearshore land slope and distance to lake centers). Next, we computed geometric depth estimates (Equation 1) and offsets to these estimates using the random forest algorithm (Equation 2). Covariates used in offset modeling included a variety of lake, watershed, and hydrologic subbasin measures that are available for all lakes (Table 1). We examined differences in overall prediction error corresponding to different inputs to geometric depth as well as differences in the relative distribution of prediction error in lakes with different characteristics.

Given that, by definition, the distance proxy (distance to the center of the lake) must always be greater or equal to the true distance value (distance to the deepest point of the lake), we expect that the use of this proxy will lead to overestimation of lake depth (Figure 1). Furthermore we expect to see greater overestimation error in reservoirs as compared to natural lakes because many reservoirs are known to be drowned river valleys where the deepest point is close to the edge at the end of the reservoir (i.e. next to the dam) rather than in the center of the reservoir \citep{lanza1985interactions}. Similar to distance proxies, we expect that the use of a nearshore land slope proxy will lead to prediction error according to differences in cross-section shape (Figure 2) such that the depth of U-shaped (i.e. concave) lakes will be overpredicted whereas the depth of V-shaped (i.e. convex) lakes will be underpredicted. Finally, we expect that offsets to geometric depth estimates will be most strongly related to lake area and hydrologic subbasin variables as these measures have been influential in prior studies \citep{oliver2016prediction}.

## METHODS
### Data description
We compiled bathymetry data on approximately 5,000 lakes in the Northeastern and Midwestern US from nine official state databases (Figure S1). The original data came in a variety of formats including pre-interpolated rasters (Minnesota), contour lines (Nebraska, Michigan, Massachusetts, Kansas, Iowa), contour polygons (New Hampshire, Connecticut), or point depth soundings (Maine). For the Minnesota data, we simply clipped the raster for each lake to its outline. For data from the remaining states, we processed each lake by converting its original representation to a point layer (if necessary), rasterizing these points, and creating an interpolated bathymetry “surface” using a simple moving window average in the raster R package \citep{hijmansRasterGeographicData2019}. The size of the moving window was adjusted iteratively to ensure that each bathymetry raster contained no missing data. 

All lake bathymetry was specifically calculated relative to high-resolution (1:24,000 scale) NHD \citep{usgsNationalHydrographyDataset2019} waterbodies such that source data and bathymetry surface outputs were clipped to the area of each lake polygon. We restricted the lakes in our study to those with an area of at least 4 ha and a maximum depth of at least 0.3 m (1 ft). The purpose of these restrictions was to ensure that lakes had enough contours (or points, or polygons) to generate adequately smooth interpolations with which to calculate in-lake geometry metrics. 

We used our generated bathymetry surfaces to find the location of the deepest point in the lake and we resolved ties by choosing the deepest point that was closest to the center of the lake. We calculated the center of the lake not as its centroid but rather by finding the point farthest from the lake shoreline (i.e. its “visual distance to lake center”). For these calculations, we used the polylabelr R package \citep{larssonPolylabelrFindPole2019d}, which interfaces with the Mapbox pole of inaccessibility algorithm \citep{agafonkinJSLibraryFinding2019}. We calculated in-lake slope as maximum lake depth divided by the distance to the deepest point and we calculated nearshore land slope for each lake by computing the slope within a 100-m buffer using data from a high resolution digital elevation model (~15x15m grain) accessed using the elevatr R package \citep{hollisterElevatrAccessElevation2017} and the terrain function in the raster R package \citep{hijmansRasterGeographicData2019}.

We categorized lakes based on their cross-section shape and reservoir class. For cross-section shape, we categorized lakes as either convex or concave following the method of \citet{hakansonLakeFormLake1977} by computing normalized lake depth-area relationships (i.e. hypsographic curves) and assigning class membership based on whether a lake’s curve falls above or below that of a simple straight-sided cone (Figure S4). We further classified lakes using data from \citet{polus2020}, which uses the output of a machine learning algorithm to assign a probability to each lake regarding whether it is a reservoir or a natural lake. For our purposes, we determined a lake to be a reservoir if the classification probability was 0.75 or greater. The \citet{polus2020} data product defines reservoirs as any permanent waterbody that has a water control structure likely to significantly impact flow or pool water, beyond simply controlling water level. It makes no distinction between different dam types or dam heights.

Covariates used in random forest modeling (Table 1, Equation 2) for lake elevation, area, island area, perimeter, shoreline development, watershed to lake area ratio, and hydrologic subbasin (i.e. HUC4s), were obtained from the LAGOS-US LOCUS database (Smith et al. In Prep). Shoreline development is a measure of lake perimeter shape defined as:

\begin{align}
shoreline_{devel} = perimeter / (2 * \sqrt{(\pi * waterarea * 10000)})        
\end{align}

where sinuous lakes have larger values of shoreline development and circular lakes have smaller values of shoreline development. Watershed to lake area ratio is an approximation of water residence time and is defined as watershed area divided by lake area. All of our data and data processing code are available at [Zenodo DOI].

2.2. Proxy evaluation
We conducted a qualitative assessment of whether or not proxy measures of lake geometry are representative of their true values by visual inspection (i.e. plotting each proxy measure against its corresponding true value) and by computing coefficients of determination ($R^2$). We further tested proxy measures by examining their effect on lake depth prediction error. Our approach involved several steps. In the first step, we computed a geometric estimate of lake depth using only geometry information (depth_geometric, Equation 1). In the second step, we fit a random forest model to predict observed (i.e. true) depth as a function of geometric depth along with several covariates available for all lakes (Table 1). The purpose of this random forest “offset” modeling was to more rigorously test our expectations regarding prediction error among different formulations of depth_geometric and among different lake types. Each of these steps were executed iteratively for each combination of true and proxy values of slope and distance (Table 2). 

## Model description
### Geometric model 
We used a geometric model of lakes where basins are treated as cones with a fixed relationship between slope and distance (Equation 1). Note that Equation 1 is a geometric formula and has no intercept or “coefficients” and it produces a perfect depth estimate given true values of slope and distance. To use this model to predict the depth of all lakes, there is a necessary assumption that proxy slope and distance measures, which are available for all lakes, are representative of true slope and distance (Figure 1).

### Random forest models
Nearly all prior studies predicting lake depth using geometric models include a statistical or machine learning model “layer” or “offset” to boost predictive accuracy. For our purposes, this offset modeling enabled us to test our expectations that prediction error would be different among different formulations of depth_geometric and among different lake types. It also facilitated direct comparison against prior models of lake depth including those that are non-geometric. We generated an “offset” to geometric depth (sensu Hollister 2011) using the random forest algorithm and the ranger R package \citep{wrightRangerFastImplementation2017} to predict observed maximum depth as a function of covariates including geometric maximum depth (from Equation 1) along with the lake elevation, area, perimeter, and ratio/index measures listed in Table 1:

\begin{align}
  depth_{observed} ~ depth_{geometric} + covariates         
\end{align}

Neither cross-section shape nor reservoir class was used as a covariate in any random forest models. We used the random forest algorithm because it makes no assumptions about the distribution of model residuals, allows for non-linearity, and is insensitive to interactions (i.e. multicollinearity) among covariates \citep{prasadNewerClassificationRegression2006}. 

### Model comparisons
We tested model sensitivity to slope and distance proxies by generating multiple “geometric maximum depth” estimates from 3 different model runs using each of the possible metric combinations for Equation 1 (true slope - proxy distance, proxy slope - true distance, proxy slope - proxy distance). Prior to entry into Equation 1, we standardized proxy distances to have the same numeric range as their true counterpart. The purpose of this standardization was to prevent lakes with extremely long proxy distances from having an outsized impact on model evaluation metrics. 

### Model evaluations
We evaluated model fit and prediction error using root-mean-square error (RMSE) and coefficient of determination ($R^2$) metrics on a holdout set containing 25\% of all lakes. We evaluated the residuals (residual = observed - predicted) of each model relative to lake cross-section shape and reservoir classes to determine whether depth is consistently over or under predicted for some lake types relative to others. All of our code for model fitting and evaluation is available at [Zenodo DOI].

## RESULTS
Lakes belonging to each cross-section shape and reservoir class were not evenly distributed across our study area (Figure S1). For example, concave lakes were nearly absent from Michigan whereas Maine lakes had an overabundance of lakes categorized as neither concave nor convex. Lakes in the southern portions of our study area tended to be classified as reservoirs whereas lakes in the northern portions of our study area were a more even mix between reservoirs and natural lakes (Figure S1). Approximately 18\%, 80\%, and 2\% of lakes were classified as having a concave, convex, or neither shape respectively whereas approximately 30\% and 70\% of lakes were classified as being a reservoir or a natural lake. 

Although proxy distance to lake center was often much larger in magnitude compared to the true distance to the deepest point of lakes’, they were strongly related ($R^2$ = 0.8). In contrast, proxy nearshore land slope and true in-lake slope were more weakly related ($R^2$ = 0.17). For slope measures, most lakes had lower magnitude (i.e. shallower) nearshore land slope compared to true in-lake slope (Figure 3). Taken together, these results suggest that proxy distance to the center of lakes is representative of true distance to the deepest point of lakes while proxy nearshore land slope is not representative of true in-lake slope. In addition to overall differences between slope and distance measures, we found differences in these relationships among lake shape classes. For example, in-lake slope and distance to the deepest point of the lake metrics were consistently larger in magnitude for convex lakes as compared to concave lakes (Figure S5). However,  there were not similar differences among slope and distance metrics for natural lakes versus reservoirs (Figure S5). 

The use of proxy nearshore land slope had a larger effect on model fit and prediction error than the use of proxy distance to lake center (Table 2). More specifically, the true slope - proxy distance model had a better fit (R2 = 0.73) and lower prediction error (RMSE = 4.23m) compared to the proxy slope - true distance model (R2 = 0.26, RMSE = 6.87m). Furthermore, analysis of model residuals showed overestimation of lake depth for concave lakes when models included a proxy slope measure (Figure 4). We observed similar but smaller overestimation depending on if a lake was classified as a reservoir rather than a natural lake (Figure 4). 

The most important covariates in offset models were those relating to spatial location, lake area, and perimeter (Figure S6). Conversely, watershed metrics and lake elevation had little contribution to random forest model fit (Figure S6). The spatial location (i.e. HUC4) covariate was notably less importance in the true slope model compared to the two proxy slope models. Model importance calculations indicated that omitting a geometric max depth measure results in a 130\%, 60\%, or 50\% increase in mean square error depending on the formulation of geometric max depth in Eq 1 (Figure S6). 
