---
output: pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 6.5, fig.height = 5)
# setwd("figures")
source("../scripts/99_utils.R")
```

```{r 01_heatmap, echo=FALSE, message=FALSE, eval=TRUE, warning=FALSE, results='hide'}
library(corrr)
library(pheatmap)
library(recipes)

dt_raw_ne <- read.csv("../data/lagosne_depth_predictors.csv", 
                      stringsAsFactors = FALSE)

dt_raw_ne_normal_rec <- recipe(. ~ ., data = dt_raw_ne) %>%
  step_normalize(all_numeric()) %>%
  prep()
dt_raw_ne_normal <- juice(dt_raw_ne_normal_rec)

create_heatmap <- function(x){
  print(range(x$lake_maxdepth_m))
  pretty_names <- gsub("mbgconhull_", "", names(x))
  pretty_names <- gsub("lake_", "", pretty_names)
  pretty_names <- gsub("_nounits", "", pretty_names)
  pretty_names <- gsub("focallake", "", pretty_names)
  
  test <- x %>%
    setNames(pretty_names) %>%
    dplyr::select_if(is.numeric) %>%
    dplyr::select(-lagoslakeid, -contains("decdeg"),
                  -contains("nhd"),
                  -contains("lagoslakeid"),
                  -huc12) %>%
    correlate() %>%
    data.frame()
  test_rowname    <- test$rowname
  test            <- dplyr::select(test, -rowname)
  row.names(test) <- test_rowname
  
  pheatmap(t(test),
          color = colorRampPalette(
            RColorBrewer::brewer.pal(n = 7, name = "Reds"))(100))
}

create_heatmap(dt_raw_ne)
create_heatmap(dt_raw_ne_normal)
```

```{r metric_correlations_setup, echo=FALSE, warning=FALSE}

dt <- dplyr::select(dt_raw_ne, names(dt_raw_ne)[names(dt_raw_ne) %in%
                    c("lake_meandepth_m", 
              names(readRDS("../data/01_depth_model/depth_training.rds")))])
names(dt) <- gsub("^lake_", "", names(dt))

gg_slope <- jsta::jheatmap(dt, focal_columns = "inlake_slope")$gtable
gg_dist <- jsta::jheatmap(dt, focal_columns = "dist_deepest")$gtable
```

```{r metric_correlations, echo=FALSE, warning=FALSE}
cowplot::plot_grid(
  gg_slope, 
  gg_dist, 
  rel_widths = c(1, 0.95))
```
