---
output:
  pdf_document
header-includes: 
  - \pagenumbering{gobble}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
# setwd("figures")
```

```{r summary_table, eval=TRUE}
library(kableExtra)
suppressMessages(library(dplyr))
library(magrittr)
library(stringr)

# setwd("tables")
nearshore <- read.csv("../data/00_geometry/nearshore.csv", 
                      stringsAsFactors = FALSE) %>%
  dplyr::select(llid, contains(c("slope_mean", "slope_online_mean", 
                                 "slopes_mean", "slopes_online_mean")))
dt_all <- read.csv("../data/lagosus_depth_predictors.csv", 
               stringsAsFactors = FALSE) %>%
  distinct(lagoslakeid, .keep_all = TRUE) %>%
  dplyr::select(-matches("inlake_slopes_online"), 
                -matches("inlake_slope_online"), 
                -matches("inlake_slope_mean"),
                -lake_centroidstate.y, 
                -lake_centroidstate.x)
dt_bathy <- dt_all %>%
  right_join(nearshore, by = c("lagoslakeid" = "llid")) %>%
  dplyr::select(-contains("lagoslakeid"), 
                -contains("lake_nhd"), 
                -contains("lake_huc"))

compute_stats <- function(dt){
  # dt <- dt_raw
  dt <- dt %>%
  tidyr::gather(key = "variable") %>%
  group_by(variable) %>%
  mutate(value = as.numeric(value)) %>%
  mutate(q10 = quantile(value, probs = c(0.1), na.rm = TRUE),
         q25 = quantile(value, probs = c(0.25), na.rm = TRUE),
         q50 = quantile(value, probs = c(0.5), na.rm = TRUE),
         q75 = quantile(value, probs = c(0.75), na.rm = TRUE),
         q90 = quantile(value, probs = c(0.9), na.rm = TRUE), 
         ratio = q90 / q10, 
         n = sum(!is.na(value), na.rm = TRUE)) %>%
  dplyr::filter(!is.na(q50)) %>%
  dplyr::distinct(signif(q10, 2), signif(q25, 2), signif(q50, 2), signif(q75, 2), signif(q90, 2), ratio, n) %>%
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  dplyr::select(variable, 
         q10 = `signif(q10, 2)`,
         q25 = `signif(q25, 2)`,
         q50 = `signif(q50, 2)`,
         q75 = `signif(q75, 2)`,
         q90 = `signif(q90, 2)`,
         q10_q90_ratio = ratio,
         n)#  %>%
  # left_join(dt_units, by = "variable") %>%
  # dplyr::select(variable, units, everything())

  dt <- ungroup(dt)
  # dt <- left_join(dt, pred_key, by = c("variable" = "var"))
  # dt <- dplyr::filter(dt, !is.na(pretty))
  
  # dt <- mutate(dt, pretty = case_when(
  #   nchar(units) > 0 ~ paste0(pretty, " (", units, ")"),
  #   TRUE ~ pretty), 
  #   IQR = paste0(q25, " - ", q75))
  dt <- dplyr::select(dt, variable, # Variable = pretty,
                      Median = q50, Q25 = q25, Q75 = q75, n)
  dt
}

# compute stats for bathymetry lakes
dt_bathy <- compute_stats(dt_bathy)
dt_bathy <- data.frame(dt_bathy)
# round geometry measures to two decimal points
clean_geometry <- function(x) as.character(round(as.numeric(x), 2))
dt_bathy$Median[which(dt_bathy$variable == "inlake_slope_pnt"):nrow(dt_bathy)] <-
  clean_geometry(
    dt_bathy$Median[which(dt_bathy$variable == "inlake_slope_pnt"):nrow(dt_bathy)])
dt_bathy$Q25[which(dt_bathy$variable == "inlake_slope_pnt"):nrow(dt_bathy)] <-
  clean_geometry(
    dt_bathy$Q25[which(dt_bathy$variable == "inlake_slope_pnt"):nrow(dt_bathy)])
dt_bathy$Q75[which(dt_bathy$variable == "inlake_slope_pnt"):nrow(dt_bathy)] <-
  clean_geometry(
    dt_bathy$Q75[which(dt_bathy$variable == "inlake_slope_pnt"):nrow(dt_bathy)])
  
# compute stats for all of lagosus
dt_all <- data.frame(compute_stats(dt_all))
dt_all <- dplyr::filter(dt_all, variable %in% dt_bathy$variable)

# interleave
dt_combined <- suppressMessages(
  bind_cols(lapply(names(dt_bathy)[2:5], 
                           function(i) paste0(dt_bathy[,i], 
                                              " (", dt_all[,i], ")")))
  ) %>%
  setNames(names(dt_bathy)[2:5])

dt_combined <- bind_cols(
  dplyr::select(dt_bathy, variable), 
  dt_combined)

# knitr::kable(dt, digits = 0, format = "markdown") 
#%>%
 # add_header_above(c(" ", " ", Ranges = 3, " ", " "))
```

```{r predictors_table}
# setwd("figures")
# dt_combined$variable
exclude_vars <- unique(dt_combined$variable)[
  stringr::str_detect(unique(dt_combined$variable), 
                     "totalarea|islandperimeter|between|buffer100m|lake_meandepth_m|countyfips|upstream|length_m|width_m|orientation_deg|nws_")]
slope_distance_vars <- unique(dt_combined$variable)[
  stringr::str_detect(unique(dt_combined$variable), 
                     "dist_|e_slope_|dists_|e_slopes")]
slope_distance_vars <- slope_distance_vars[!slope_distance_vars %in% exclude_vars]

dt <- dt_combined %>%
  dplyr::filter(variable %in% c(slope_distance_vars, 
                           "lake_maxdepth_m", "lake_elevation_m",
                           "lake_perimeter_m", "lake_shorelinedevfactor",
                           "ws_lake_arearatio", "lake_islandarea_ha", 
                           "lake_waterarea_ha"))
# dt$variable
                       # %>%
  # mutate(n = dt_bathy$n[which(dt_bathy$variable == "inlake_slope")])

# remove sample size reporting for bathy specific variables
dt[
  dt$variable %in% slope_distance_vars, 2:5] <- 
  dt[
  dt$variable %in% slope_distance_vars, 2:5] %>%
apply(2, function(x) stringr::str_replace(x, "\\(([^\\)]+)\\)", "(-)"))

taxonomy_key <- read.csv("../data/taxonomy.csv", stringsAsFactors = FALSE)

# dt$variable[!dt$variable %in% taxonomy_key$col_name]

dt <- left_join(dt, taxonomy_key, by = c("variable" = "col_name")) %>%
  dplyr::mutate(variable = pretty) %>% select(-pretty, -description)

dt[11:18,] <- dplyr::arrange(dt[11:18,], variable)

dt <- dplyr::rename(dt, Variable = variable)

model_predictors <- data.frame(
  variable = names(read.csv("../data/depth_predictors.csv", 
                            stringsAsFactors = FALSE)), 
  stringsAsFactors = FALSE) %>%
  dplyr::filter(variable != "lake_maxdepth_m") %>%
  left_join(taxonomy_key, by = c("variable" = "col_name")) %>%
  pull(pretty) %>% na.omit() %>% as.character()
  
  
# bold Eq 2 predictor variables
dt_md <- dt
dt_md$Variable[
  dt_md$Variable %in% model_predictors & !is.na(dt_md$Variable)] <- 
  paste0("**", 
dt_md$Variable[
  dt_md$Variable %in% model_predictors & !is.na(dt_md$Variable)],
         "**")

options(knitr.kable.NA = '-')
knitr::kable(dt_md, digits = 0, format = "markdown")

# ---- latex output ----

# bold Eq 2 predictor variables
dt$Variable[
  dt$Variable %in% model_predictors & !is.na(dt$Variable)] <- 
  paste0("\\textbf{", 
dt$Variable[
  dt$Variable %in% model_predictors & !is.na(dt$Variable)],
         "}")

if(interactive()){
  clipr::write_clip(
    gsub("%\\*\\*", "\\\\%\\*\\*",
    gsub("_", "\\\\_",
    gsub("%\\\\", "\\\\%\\\\",
    sub("\\\\midrule", "\\\\hline",
    sub("\\\\bottomrule", "\\\\hline",
    sub("\\\\toprule", "\\\\hline",
        knitr::kable(dt, digits = 2, format = "latex",
       booktabs = TRUE, linesep = "", align = c("l"), escape = FALSE)))))))
     )
}
```
