---
output:
  pdf_document
header-includes: 
  - \pagenumbering{gobble}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 5, fig.height = 6)
# setwd("tables")
```

```{r 02_model_metrics, eval=TRUE}
library(kableExtra)
suppressMessages(library(dplyr))
library(magrittr)
library(stringr)

tidy_grid_metrics <- function(x) {
  res <- x %>%
    mutate_if(is.numeric, function(x) as.character(round(x, 2))) %>%
    mutate(rsq = as.numeric(rsq)) %>%
    mutate(rsq = case_when(
      as.character(model) == "maxdepth_true_true" ~ NA_real_,
      TRUE ~ rsq)) %>%
    mutate(rmse = round(as.numeric(rmse), 1)) %>%
    mutate(rmse = case_when(
      as.character(model) == "maxdepth_true_true" ~ NA_character_,
      TRUE ~ paste0(rmse, " m"))) %>%
    mutate(mape = as.numeric(mape)) %>%
    mutate(mape = case_when(
      as.character(model) == "maxdepth_true_true" ~ NA_character_,
      TRUE ~ paste0(round(mape, 0), " %"))) %>%
    mutate(model = gsub("maxdepth_", "", model)) %>%
    mutate(model = gsub("false", "proxy", model)) %>%
    tidyr::separate(model, c("slope", "distance")) %>%
    dplyr::select(slope, distance, everything(), -.estimator)
  res
}

dt_raw <- readRDS("../data/01_depth_model/depth_grid_metrics.rds")
dt_metrics <- lapply(dt_raw, tidy_grid_metrics)
dt_metrics <- do.call("rbind", dt_metrics)
dt_metrics$filter <- ""
dt_metrics$filter[c(1, 5, 9, 13, 17)] <- c("all", "reservoir", "natural lake", "convex", "concave")
# dt_metrics$filter <- c(rep("all", 4), rep("reservoir", 4),
#   rep("natural lake", 4), rep("convex", 4), rep("concave", 4))
dt_metrics <- dplyr::relocate(dt_metrics, filter)

options(knitr.kable.NA = "-")
knitr::kable(dt_metrics, digits = 2, format = "markdown")

# clipr::write_clip(
#   knitr::kable(dt_metrics, format = 'latex', align = c("llll"),
# escape = TRUE))
# flextable::save_as_docx(flextable::flextable(dt_metrics), path = "../manuscript/inland_waters/table2.docx")
```

\clearpage

```{r 02_model_sensitivity, eval=TRUE}
dt_metrics_sensitivity <- lapply(
  readRDS("../data/01_depth_model/depth_grid_metrics.rds"), function(x)
    tidy_grid_metrics(x))

labels <- c("All", "Res only", "NL only", "convex only", "concave only")
dt_metrics_sensitivity <- lapply(
  seq_len(length(dt_metrics_sensitivity)), function(i) {
    res <- dplyr::mutate(dt_metrics_sensitivity[[i]], label = labels[i]) %>%
      dplyr::relocate(label)
    res$label[2:4] <- NA
    res
  })

options(knitr.kable.NA = "-")
knitr::kable(do.call("rbind", dt_metrics_sensitivity),
  digits = 2, format = "markdown")
```

\clearpage

```{r 02_alternate_metrics, eval=TRUE}

dt_metrics <- read.csv("../data/01_depth_model/alternatives_metrics.csv",
  stringsAsFactors = FALSE) %>%
  mutate_if(is.numeric, function(x) as.character(round(x, 2))) %>%
  mutate(proxy_proxy_rmse = paste0(
    round(as.numeric(proxy_proxy_rmse), 1), " m")) %>%
  mutate(proxy_proxy_rsq = round(as.numeric(proxy_proxy_rsq), 2)) %>%
  mutate(proxy_proxy_mape = paste0(
    round(as.numeric(proxy_proxy_mape), 0), " %")) %>%
  mutate(inlake_slope = gsub("inlake_", "", inlake_slope)) %>%
  mutate(nearshore_slope = gsub("nearshore_", "", nearshore_slope)) %>%
  arrange(proxy_proxy_rmse) %>%
  setNames(c("Inlake slope", "Nearshore slope",
    "Inlake distance", "RMSE", "$R^2$", "MAPE"))

options(knitr.kable.NA = "-")
knitr::kable(dt_metrics, digits = 2, format = "markdown")

# dt_metrics[2,] <- paste0("**", dt_metrics[2,], "**") # highlight row from main text
# clipr::write_clip(
#   gsub("%\\*\\*", "\\\\%\\*\\*",
#   gsub("_", "\\\\_",
#   gsub("%\\\\", "\\\\%\\\\",
#   sub("\\\\midrule", "\\\\hline",
#   sub("\\\\bottomrule", "\\\\hline",
#   sub("\\\\toprule", "\\\\hline",
#       knitr::kable(dt_metrics, digits = 2, format = "latex",
#      booktabs = TRUE, linesep = "", align = c("lllllc"), escape = FALSE)))))))
#    )
```
